name: lifelink
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  flutter_spinkit: ^5.2.0
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9
  geolocator: ^11.0.0
  provider: ^6.1.5+1
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/interfont.ttf
  assets:
    - assets/images/

  